### ISSUE TITLE
Excerpt has no indication that post continues

### ISSUE THREAD

**Issue by Hoplake** [Postleaf/empower-theme#3]
When making an excerpt to the blog post list, Empower theme doesn't seem to make any kind of marking that the article continues, like "click here to continue reading" etc.  

Am I missing something and is it intentional ?

**Comment by claviska** [comment]
That's by design. You can add a "read more" link to [`loop.dust`](https://github.com/Postleaf/empower-theme/blob/master/templates/partials/loop.dust#L13-L16) if you want:

```html
{! Excerpt !}
<div class="loop-excerpt">
  {@excerpt paragraphs="2"/}
  <a href="{@url type="post" slug=slug/}">Read more</a>
</div>
```

The default theme is really just an example of how to theme Postleaf, so feel free to customize away.
